### ISSUE TITLE
Cursor theme broke on Gnome on last update.

### ISSUE THREAD

**Issue by zer09** [keeferrourke/capitaine-cursors#16] opened 2017-10-23 02:17 UTC
Hello good day, I think the cursor theme is broken in Gnome.

I took me few days to identify the issue, why gnome shell is kicking me out back to GDM when I tried to login.

If I use the cursor theme on gnome shell, I cant login anymore. I also tried it in gnome using Xorg, the cursor theme is not working, and it will just use the default cursor.

Steps:
1. When logged in using xorg, trying to use la capitatine and it doesn't work.
2. Change to other cursor theme, or set to default, and their theme is working.
3. log-out then login again using Wayland, and you can successfully logged in.
4. Change back the cursor theme to la capitaine using tweak tool, then wayland will crash and kick back to GDM.
5. Try to login again in wayland, but it will just loop back to GDM.

If I remembered it correctly it just happened after dnf pull the new update of the theme.

Thanks.

**Comment by keeferrourke** [comment] 2017-10-23 14:51
@zer09 There is no way this is caused by the cursor theme. Submit a bug report to redhat.bugzilla.org under the GNOME product. GNOME 3.26.1 is not currently in a stable state on Fedora 27.

Additionally, I'm also running Fedora 27 beta with GNOME Shell and frequently switch between Wayland and Xorg and no such error can be provably caused by a cursor theme. GNOME is crashing all over the place right now, see these bugs: [1390198](https://bugzilla.redhat.com/show_bug.cgi?id=1390198), [1469813](https://bugzilla.redhat.com/show_bug.cgi?id=1469813), etc.

Closing as not a bug.

**Closed by keeferrourke** 2017-10-23 14:51 UTC
